### ISSUE TITLE
Allow user to change parameters?

### ISSUE THREAD

**Issue by Hoeze** [jupyterhub/wrapspawner#31]
Hi, I'd like to allow the user to change some of the batch spawn parameters, e.g. "memory between 1GB and 24GB". Is this possible with wrapspawner?

**Comment by rkdarst** [comment]
I think you already see how to use ProfileSpawner as it's designed.  Currently there aren't other ways to pass custom fields - at that point I think most people would do their own `user_options` stuff.  Maybe there's another spawner that can do this automatically without subclassing/parsing HTML.  Like maybe https://github.com/ResearchComputing/jupyterhub-options-spawner ?

**Comment by statiksof** [comment]
@rkdarst I have tried https://github.com/ResearchComputing/jupyterhub-options-spawner. 
The spawner does not update the child_config when changing the file on disk. ```wrapspawner``` continues using the first config. 

Applying the path #32 didn't solve the problem.
