### ISSUE TITLE
Missing admin access to repo

### ISSUE THREAD

**Issue by mbmilligan** [jupyterhub/wrapspawner#40]
It looks like I never was made an admin on this repository when we split it from Batchspawner. Only noticing now that I want access to the settings tab to investigate Actions workflows for making releases. 

@willingc it looks like you originally created this repo?

**Comment by willingc** [comment]
Added @mbmilligan. You should now have a GitHub email to accept admin rights. :sunny:

**Comment by mbmilligan** [comment]
Reopening - looks like I'm still missing some access rights. I don't have access to the "secrets" tab under Settings, which is needed to set up a PYPI auth token. 

Tagging @willingc again. Based on the options I can see under Settings, it looks like I have some kind of moderator role, not an admin one.

**Comment by willingc** [comment]
Sorry @mbmilligan I had clicked maintain last time. I have just changed that to admin. You should be able to perform admin functions on this repo now.

**Comment by mbmilligan** [comment]
That seems to have done it. Thanks!
