### ISSUE TITLE
Question: Can I create a dynamic list of profiles?

### ISSUE THREAD

**Issue by squaresurf** [jupyterhub/wrapspawner#5]
I have extended the ProfilesSpawner class to create a Spawner class that will add profiles for all docker images on the local machine that have a jupyterhub tag. The biggest issue I currently have is that it will only build the profiles form once, in other words, I have to restart jupyterhub in order to get new docker images to show up. Is there a lifecycle hook that would be a better place for me to dynamically add profiles?

Here is a link to my custom class: https://github.com/verypossible/wrapspawner/blob/feature/docker-profile-spawner/wrapspawner/wrapspawner.py#L218

**Comment by squaresurf** [comment]
I'm sorry if there is a better place to ask this question. I'm very willing to move this q to another location.

**Comment by squaresurf** [comment]
I've figured this out by using a `@property` decorator for `options_form`.

If that is a bad idea for some reason, feel free to reopen this discussion :smile:.

**Comment by minrk** [comment]
Property is a fine solution!

**Comment by squaresurf** [comment]
Awesome! Thank you for the confirmation @minrk.
